#pragma once

#include "Utils/Types.h"

// Auto-generated from ShareDir/generate_packet_ids.js
enum class PacketId : uint32
{
	C_LOGIN = 1,
	S_LOGIN = 2,
	C_ENTER_GAME = 3,
	C_PLAYER_MOVE = 4,
	C_CHAT = 5,
	C_REQUEST_USE_SKILL = 6,
	S_ENTER_GAME = 7,
	S_PLAYER_LIST = 8,
	S_PLAYER_MOVE = 9,
	S_CHAT = 10,
	S_PLAYER_LEAVE = 11,
	S_PLAYER_SPAWN = 12,
	S_REQUEST_USE_SKILL = 13,
	S_MOVE_CORRECTION = 14,
	S_ERROR = 15,
	S_MONSTER_SPAWN = 16,
	S_MONSTER_MOVE = 17,
	S_MONSTER_DESPAWN = 18,
	S_MONSTER_LIST = 19,
	S_MONSTER_STATE = 20,
	S_MONSTER_ATTACK = 21,
	S_HITSCAN_ATTACK = 22,
	S_PLAYER_HP = 23,
	S_PROJECTILE_SPAWN = 24,
	S_PROJECTILE_HIT = 25,
	S_PROJECTILE_DESTROY = 26,
	SS_VALIDATE_TOKEN = 27,
	SS_VALIDATE_TOKEN_RESULT = 28,
};
