#pragma once

#include "Utils/Types.h"

// Auto-generated from ShareDir/generate_packet_ids.js
enum class PacketId : uint32
{
	C_LOGIN = 1,
	S_LOGIN = 2,
	C_ENTER_GAME = 3,
	C_PLAYER_MOVE = 4,
	C_CHAT = 5,
	C_USE_SKILL = 6,
	C_MOVE_COMMAND = 7,
	C_STOP_MOVE = 8,
	S_ENTER_GAME = 9,
	S_PLAYER_LIST = 10,
	S_PLAYER_MOVE = 11,
	S_UNIT_POSITIONS = 12,
	S_CHAT = 13,
	S_PLAYER_LEAVE = 14,
	S_PLAYER_SPAWN = 15,
	S_REQUEST_USE_SKILL = 16,
	S_MOVE_CORRECTION = 17,
	S_ERROR = 18,
	S_MONSTER_SPAWN = 19,
	S_MONSTER_MOVE = 20,
	S_MONSTER_DESPAWN = 21,
	S_MONSTER_LIST = 22,
	S_MONSTER_STATE = 23,
	S_SKILL_HIT = 24,
	S_SKILL_CAST_START = 25,
	S_SKILL_CAST_CANCEL = 26,
	S_UNIT_HP = 27,
	S_PROJECTILE_SPAWN = 28,
	S_BUFF_APPLIED = 29,
	S_BUFF_REMOVED = 30,
	S_PROJECTILE_DESTROY = 31,
	SS_VALIDATE_TOKEN = 32,
	SS_VALIDATE_TOKEN_RESULT = 33,
};
