#pragma once

#include "Utils/Types.h"

// Auto-generated from ShareDir/generate_packet_ids.js
enum class PacketId : uint32
{
	C_LOGIN = 1,
	S_LOGIN = 2,
	C_ENTER_GAME = 3,
	C_PLAYER_MOVE = 4,
	C_CHAT = 5,
	C_REQUEST_USE_SKILL = 6,
	C_MOVE_COMMAND = 7,
	C_STOP_MOVE = 8,
	S_ENTER_GAME = 9,
	S_PLAYER_LIST = 10,
	S_PLAYER_MOVE = 11,
	S_CHAT = 12,
	S_PLAYER_LEAVE = 13,
	S_PLAYER_SPAWN = 14,
	S_REQUEST_USE_SKILL = 15,
	S_MOVE_CORRECTION = 16,
	S_ERROR = 17,
	S_MONSTER_SPAWN = 18,
	S_MONSTER_MOVE = 19,
	S_MONSTER_DESPAWN = 20,
	S_MONSTER_LIST = 21,
	S_MONSTER_STATE = 22,
	S_MONSTER_ATTACK = 23,
	S_HITSCAN_ATTACK = 24,
	S_PLAYER_HP = 25,
	S_PROJECTILE_SPAWN = 26,
	S_PROJECTILE_HIT = 27,
	S_PROJECTILE_DESTROY = 28,
	SS_VALIDATE_TOKEN = 29,
	SS_VALIDATE_TOKEN_RESULT = 30,
};
