# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto
# Protobuf Python Version: 5.29.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    5,
    '',
    'common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x05Proto\"*\n\x07Vector3\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"\x1d\n\tTimestamp\x12\x10\n\x08\x65poch_ms\x18\x01 \x01(\x03*\xb9\x01\n\tErrorCode\x12\x06\n\x02OK\x10\x00\x12\x0b\n\x07UNKNOWN\x10\x01\x12\x18\n\x14LOGIN_SERVER_OFFLINE\x10\x64\x12\x11\n\rTOKEN_INVALID\x10\x65\x12\x11\n\rTOKEN_EXPIRED\x10\x66\x12\x15\n\x10PLAYER_NOT_FOUND\x10\xc8\x01\x12\x15\n\x10INVALID_POSITION\x10\xc9\x01\x12\x14\n\x0fINVALID_REQUEST\x10\x84\x07\x12\x13\n\x0eINTERNAL_ERROR\x10\x85\x07\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ERRORCODE']._serialized_start=99
  _globals['_ERRORCODE']._serialized_end=284
  _globals['_VECTOR3']._serialized_start=23
  _globals['_VECTOR3']._serialized_end=65
  _globals['_TIMESTAMP']._serialized_start=67
  _globals['_TIMESTAMP']._serialized_end=96
# @@protoc_insertion_point(module_scope)
