# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: game.proto
# Protobuf Python Version: 5.29.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    5,
    '',
    'game.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ngame.proto\x12\x05Proto\x1a\x0c\x63ommon.proto\"\x1c\n\x0b\x43_EnterGame\x12\r\n\x05token\x18\x01 \x01(\t\"=\n\x0c\x43_PlayerMove\x12 \n\x08position\x18\x01 \x01(\x0b\x32\x0e.Proto.Vector3\x12\x0b\n\x03yaw\x18\x02 \x01(\x02\"\x19\n\x06\x43_Chat\x12\x0f\n\x07message\x18\x01 \x01(\t\"$\n\x11\x43_RequestUseSkill\x12\x0f\n\x07skillId\x18\x01 \x01(\t\"H\n\x0bS_EnterGame\x12\x11\n\tplayer_id\x18\x01 \x01(\x05\x12&\n\x0espawn_position\x18\x02 \x01(\x0b\x32\x0e.Proto.Vector3\"\x90\x01\n\x0cS_PlayerList\x12/\n\x07players\x18\x01 \x03(\x0b\x32\x1e.Proto.S_PlayerList.PlayerInfo\x1aO\n\nPlayerInfo\x12\x11\n\tplayer_id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12 \n\x08position\x18\x03 \x01(\x0b\x32\x0e.Proto.Vector3\"P\n\x0cS_PlayerMove\x12\x11\n\tplayer_id\x18\x01 \x01(\x05\x12 \n\x08position\x18\x02 \x01(\x0b\x32\x0e.Proto.Vector3\x12\x0b\n\x03yaw\x18\x03 \x01(\x02\"<\n\x06S_Chat\x12\x11\n\tplayer_id\x18\x01 \x01(\x05\x12\x0e\n\x06sender\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"\"\n\rS_PlayerLeave\x12\x11\n\tplayer_id\x18\x01 \x01(\x05\"\"\n\x11S_RequestUseSkill\x12\r\n\x05range\x18\x01 \x01(\x05\"4\n\x10S_MoveCorrection\x12 \n\x08position\x18\x01 \x01(\x0b\x32\x0e.Proto.Vector3\"S\n\x07S_Error\x12\x18\n\x10source_packet_id\x18\x01 \x01(\r\x12\x1e\n\x04\x63ode\x18\x02 \x01(\x0e\x32\x10.Proto.ErrorCode\x12\x0e\n\x06\x64\x65tail\x18\x03 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'game_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_C_ENTERGAME']._serialized_start=35
  _globals['_C_ENTERGAME']._serialized_end=63
  _globals['_C_PLAYERMOVE']._serialized_start=65
  _globals['_C_PLAYERMOVE']._serialized_end=126
  _globals['_C_CHAT']._serialized_start=128
  _globals['_C_CHAT']._serialized_end=153
  _globals['_C_REQUESTUSESKILL']._serialized_start=155
  _globals['_C_REQUESTUSESKILL']._serialized_end=191
  _globals['_S_ENTERGAME']._serialized_start=193
  _globals['_S_ENTERGAME']._serialized_end=265
  _globals['_S_PLAYERLIST']._serialized_start=268
  _globals['_S_PLAYERLIST']._serialized_end=412
  _globals['_S_PLAYERLIST_PLAYERINFO']._serialized_start=333
  _globals['_S_PLAYERLIST_PLAYERINFO']._serialized_end=412
  _globals['_S_PLAYERMOVE']._serialized_start=414
  _globals['_S_PLAYERMOVE']._serialized_end=494
  _globals['_S_CHAT']._serialized_start=496
  _globals['_S_CHAT']._serialized_end=556
  _globals['_S_PLAYERLEAVE']._serialized_start=558
  _globals['_S_PLAYERLEAVE']._serialized_end=592
  _globals['_S_REQUESTUSESKILL']._serialized_start=594
  _globals['_S_REQUESTUSESKILL']._serialized_end=628
  _globals['_S_MOVECORRECTION']._serialized_start=630
  _globals['_S_MOVECORRECTION']._serialized_end=682
  _globals['_S_ERROR']._serialized_start=684
  _globals['_S_ERROR']._serialized_end=767
# @@protoc_insertion_point(module_scope)
